// <auto-generated />
namespace PatientDocumenation.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class RenameProviderUserIdFK : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(RenameProviderUserIdFK));
        
        string IMigrationMetadata.Id
        {
            get { return "202007091640571_RenameProviderUserIdFK"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
